package org.middleheaven.quantity.measurables;

/**
 * 
 * Represents the measurable property of a phenomenon.
 * 
 * 
 * 
	ACCELERATION,
	AMOUNT_OF_SUBSTANCE,

	ANGULAR_ACELERATION,
	ANGULAR_VELOCITY,
	ANGULAR_MOMENTUM,
	AREA,
	CATALITICACTIVITY,
	DATA_AMOUNT,
	DATA_RATE,

	DURATION,
	DYNAMIC_VISCOSITY,
	ELECTRIC_CAPACITANCE,
	ELECTRIC_CARGE,
	ELECTRIC_CONDUNCTANCE,
	ELECTRIC_CURRENCT,
	ELECTRIC_INDUTANCE,
	ELECTRIC_POTENCIAL,
	ELECTRIC_RESISTANCE,
	ENERGY,
	FORCE,
	FREQUENCY,
	ILLUMINANCE,
	KINEMATIC_VISCOSITY,
    LUMINOUS_FLUX,
    LUMINOUS_INTENSITY,
    MAGNETIC_FLUX,
    MAGNETIC_FLUX_DENSITY,
	MASS,
	MASS_FLOW_RATE,
	MOMENTUM,
    POWER,
	PRESSURE,
	RADIATION_DOSE_ABSORDED,
	RADIATION_DOSE_EFFECTIVE,
	RADIOACTIVE_ACTIVITY,
    SOLID_ANGLE,
	TEMPERATURE,

	VOLUME,
	VOLUMETIC_DENSITY,
	VOLUMETIC_FLOW_RATE;
	
 *
 */
public interface Measurable {

}
